#!/usr/bin/env php
<?php

function findAutoload(string $startDir): ?string {
    $dir = realpath($startDir);

    while ($dir && $dir !== '/') {
        $autoload = $dir . '/vendor/autoload.php';
        if (file_exists($autoload)) {
            return $autoload;
        }
        $dir = dirname($dir);
    }

    return null;
}

$autoloadPath = findAutoload(__DIR__);

if (!$autoloadPath) {
    echo "❌ Could not find vendor/autoload.php\n";
    exit(1);
}

require $autoloadPath;

use Apex\Core\Install\DockerInstaller;

DockerInstaller::copyDockerCompose();
