version: '3.8'

services:
  php:
    build:
      context: ./vendor/apex-php/core/src/Wave/Docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - apexnet

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./vendor/apex-php/core/src/Wave/Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - apexnet

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apex
      MYSQL_USER: apex
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apexnet

volumes:
  mysql_data:

networks:
  apexnet:
    driver: bridge
